# Generated by Django 5.1.2 on 2024-11-10 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
                ('name', models.CharField(max_length=500)),
                ('about', models.TextField(max_length=4000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=1000)),
                ('period', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.pages')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.pages')),
            ],
        ),
    ]
