# Generated by Django 5.1.2 on 2024-11-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_pages_experiences_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_title',
            field=models.CharField(default='Landing Page', max_length=1000),
        ),
    ]
