# Generated by Django 5.1.2 on 2024-11-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_pages_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='page_title',
        ),
    ]
